### ISSUE TITLE
Upgrade syn to 2.0

### ISSUE THREAD

**Issue by zecakeh** [WanzenBug/g2p#6]
Is there any interest to bump syn to version 2.0? It will probably bump the supported Rust version significantly (syn currently advertises support for rust 1.60+).

I did a quick test locally and it seems that involves no changes in the code.

**Comment by WanzenBug** [comment]
Does syn 2.0 offer any benefits? I don't see the need to upgrade just to bump numbers.

**Comment by zecakeh** [comment]
The main reason I am suggesting this is so that downstream projects don't have to depend on 2 versions of syn, given that a lot of crates already upgraded it to the new major version. I am not sure if there are other benefits for this crate.

**Comment by RyanSquared** [comment]
I would like to mention, at this point, out of every crate in my project that depends on `syn` (which is at least 19, directly), this is the only crate that is still on `syn 1.0`. This means if I were to perform an audit of all of my dependencies, it would take less time for me to fork this project to bump it to `syn 2.0` (I imagine, I have yet to put in the work, I'm still scoping out the requirements!) than it would take for me to audit `syn 1.0`.

While `syn 2.0` may not provide immediate benefit to this crate, it results in less source code being reviewed and less compiled code being shipped.

**Comment by WanzenBug** [comment]
Thanks. Just pushed a new 1.1.0 release.
